version: '3'

services:
  web:
    container_name: web
    image: yesjjin99/dnd-bpm
    expose:
      - "8080"
    ports:
      - "8080:8080"

  nginx:
    depends_on:
      - web
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./config/nginx
    ports:
      - "80:80"